export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_ALL_CATEGORIES = "FETCH_ALL_CATEGORIES";
export const FETCH_SINGLE_CATEGORY = "FETCH_SINGLE_CATEGORY";
// Assign category dialog data with the item selected e.g. editing, deleting
export const CAT_DIALOG_DATA = "CAT_DIALOG_DATA";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const TOGGLE_ACTIVE = "TOGGLE_ACTICE";
export const VAILDATE_CAT_NAME = "VALIDATE_CAT_NAME";
export const VALIDATE_CAT_DESCRIPTION = "VALIDATE_CAT_DESCRIPTION";
export const TOGGLE_CAT_SUBMIT = "TOGGLE_CAT_SUBMIT";
export const FRESH_STATE_CATEGORY = "FRESH_STATE_CATEGORY";
