// Authentication
export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const VALIDATE_EMAIL = "VALIDATE_EMAIL";
export const VALIDATE_PASSWORD = "VALIDATE_PASSWORD";
export const VALIDATE_CONFIRMPASS = "VALIDATE_CONFIRMPASS";
export const VALIDATE_FNAME = "VALIDATE_FNAME";
export const VALIDATE_LNAME = "VALIDATE_LNAME";
export const FRESH_STATE = "FRESH_STATE";
export const SHOW_PASSWORD = "SHOW_PASSWORD";
export const SHOW_CONFIRMPASSWORD = "SHOW_CONFIRMPASSWORD";
export const TOGGLE_SUBMITBTN = "TOGGLE_SUBMITBTN";
//
