export const FETCH_FOLLOW_DATA = "FETCH_FOLLOW_DATA";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const SET_UNFOLLOW_BUTTON = "SET_UNFOLLOW_BUTTON";
export const SET_FOLLOWERS = "SET_FOLLOWERS";
export const SET_FOLLOWING = "SET_FOLLOWING";
export const FRESH_FOLLOW = "FRESH_FOLLOW";
